### PR TITLE
using different email table, fixing loop, and adding if_platform_user logic

### PR DESCRIPTION
**Pull request by srao-civis**

### CODE REVIEW

**Comment by srao-civis** [comment]
@geneorama Just added in the new email table and the if_platform_user logic. Feel free to test and make sure it works for you

**Comment by srao-civis** [comment]
@geneorama just added in the function to autogenerate the folder/report date that we're planning to use to send out the wednesday emails

**Comment by geneorama** [comment]
@srao-civis thanks.  

Did you mean to commit the .pyc file?  

Also, I was hoping that I could comment out the dates and manually set those when I run it.

**Comment by ilstate-apps-robo** [comment]
Whoops. No, did not mean to merge the pyc (forgot to edit the .gitignore). 

Yes, you can absolutely comment out the dates and manually set them. I just wanted to show you what we'll be using on Wednesdays so we can be sure we're generating the correct links to your reports!

**Pull request merged**
